version: '3.7'

services:

  elasticsearh:
    build:
      context: ../ssss
      dockerfile: ../ssss/Dockerfile

    container_name: elasticsearch
    environment:
      node.name: "elasticsearch"
      discoery.type: "single-node"
      cluster.name: "es-docker-cluster"
      cluster.initial_master_nodes: "elasticsearch"
      bootstrap.memory_lock: "true"
      ES_JAVA_OPTS: "-Xms512m -Xmx512m"

    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ./esdata01:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
      - 9300:9300


